### ISSUE TITLE
A PEP 561 compliant package

### ISSUE THREAD

**Issue by davidatbu** [EmilStenstrom/conllu#42]
First off, thanks for this package. The API on the README looks great. Can't wait to dig in.

I've forked this repo and will add type annotations to every part that I will make use(most likely all the `.py` files in the root dir). 

If you'd like I can submit a PR to merge those type annotations back in(and this repo can be PEP 561 compliant).

**Comment by EmilStenstrom** [comment]
Hi! YES, I would definitely like to have type annotations as part of this package.

The only thing I have to think about is Python 2.7 support. 

Options:

- Adding types as comments for old Python and new Python
- Adding types for new Python, and somehow converting them to comments for old Python
- Adding types as stub files (easy to forget)
- Dropping support for old Python

I’m leaning towards the last option, simply because supporting old Python is starting to get too tricky...

**Comment by davidatbu** [comment]
If you do end up going foward with the last option, have a look at #43 , where I added inline type annotations to eveything except `compat.py` and `tests/`.

Also, expectedly, adding type annotations revealed some (what I believe are) subtle bugs:

```mypy
/home/davidat/git/conllu/conllu/serializer.py:41:27: error: Item "Addable" of "Union[Metadata, Addable]" has no attribute "items"  [union-attr]
/home/davidat/git/conllu/conllu/models.py:191:9: error: Returning Any from function declared to return "str"  [no-any-return]
```

The first one pertains to the fact that `TokenList.metadata` can in fact be a list, not necessarily a dict(the `Addable` thing is my way making mypy understand a check for the presence of an `__add__` method). 

The second error can easily be fixed by wrapping `self.token['form']` with `text()`, like `self.token['id']` is already.

**Comment by EmilStenstrom** [comment]
@davidatbu I will go forward with dropping support for Python < 3.6. I will do that in a separate step, so if you rebase from that when you're done you should get a working build. 

I still have a lot of other commitments, so speed won't be super-fast, but I'll work on it when a have a spare hour between attending to small children :)
